### ISSUE TITLE
Tutorial: running "yarn test" errors out

### ISSUE THREAD

**Issue by mrossesf** [ethereum-optimism/community-hub#17] opened 2021-02-25 23:31 UTC
I was working through the tutorial and received the following error after running the **yarn test** command in [The Tests](http://community.optimism.io/tutorial/#the-tests) section. The error output and the exact steps to reproduce are below.

**Error output:**

Compilation finished successfully
An unexpected error occurred:
Error: ganache-core tried to access safe-buffer, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: safe-buffer (via "safe-buffer")
Required by: ganache-core@npm:2.13.2 (via /Users/martinrosse/optimism-tutorial/.yarn/unplugged/ganache-core-npm-2.13.2-bd779722b4/node_modules/ganache-core/build/)

Require stack:
- /Users/martinrosse/optimism-tutorial/.yarn/unplugged/ganache-core-npm-2.13.2-bd779722b4/node_modules/ganache-core/build/ganache.core.node.js
- /Users/martinrosse/optimism-tutorial/.yarn/unplugged/ganache-core-npm-2.13.2-bd779722b4/node_modules/ganache-core/index.js
- /Users/martinrosse/optimism-tutorial/.yarn/cache/@ethereum-waffle-provider-npm-3.2.1-e13574ca9d-f66c9a1da6.zip/node_modules/@ethereum-waffle/provider/dist/cjs/MockProvider.js
- /Users/martinrosse/optimism-tutorial/.yarn/cache/@ethereum-waffle-provider-npm-3.2.1-e13574ca9d-f66c9a1da6.zip/node_modules/@ethereum-waffle/provider/dist/cjs/index.js
- /Users/martinrosse/optimism-tutorial/.yarn/cache/ethereum-waffle-npm-3.2.1-ef33b88564-10bd51b8bd.zip/node_modules/ethereum-waffle/dist/cjs/index.js
- /Users/martinrosse/optimism-tutorial/test/setup.ts
- /Users/martinrosse/optimism-tutorial/test/erc20.spec.ts
- /Users/martinrosse/optimism-tutorial/.yarn/cache/mocha-npm-7.2.0-612e500d6d-1a7a4df6b8.zip/node_modules/mocha/lib/mocha.js
- /Users/martinrosse/optimism-tutorial/.yarn/cache/mocha-npm-7.2.0-612e500d6d-1a7a4df6b8.zip/node_modules/mocha/index.js
- /Users/martinrosse/optimism-tutorial/.yarn/cache/hardhat-npm-2.0.7-90ca0b7faf-5a3624da83.zip/node_modules/hardhat/builtin-tasks/test.js
- /Users/martinrosse/optimism-tutorial/.yarn/cache/hardhat-npm-2.0.7-90ca0b7faf-5a3624da83.zip/node_modules/hardhat/internal/core/tasks/builtin-tasks.js
- /Users/martinrosse/optimism-tutorial/.yarn/cache/hardhat-npm-2.0.7-90ca0b7faf-5a3624da83.zip/node_modules/hardhat/internal/core/config/config-loading.js
- /Users/martinrosse/optimism-tutorial/.yarn/cache/hardhat-npm-2.0.7-90ca0b7faf-5a3624da83.zip/node_modules/hardhat/internal/cli/cli.js
    at internalTools_makeError (/Users/martinrosse/optimism-tutorial/.pnp.js:15627:34)
    at resolveToUnqualified (/Users/martinrosse/optimism-tutorial/.pnp.js:16592:23)
    at resolveRequest (/Users/martinrosse/optimism-tutorial/.pnp.js:16684:29)
    at Object.resolveRequest (/Users/martinrosse/optimism-tutorial/.pnp.js:16762:26)
    at Function.external_module_.Module._resolveFilename (/Users/martinrosse/optimism-tutorial/.pnp.js:15860:34)
    at Function.external_module_.Module._load (/Users/martinrosse/optimism-tutorial/.pnp.js:15725:48)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/martinrosse/optimism-tutorial/.yarn/unplugged/ganache-core-npm-2.13.2-bd779722b4/node_modules/ganache-core/build/ganache.core.node.js:1:67447)
    at __webpack_require__ (/Users/martinrosse/optimism-tutorial/.yarn/unplugged/ganache-core-npm-2.13.2-bd779722b4/node_modules/ganache-core/build/webpack:/Ganache/webpack/bootstrap:9:5)

**Steps to reproduce:**

1. Clone the optimism-tutorial repo.
2. In a macOS terminal, at the home directory run: **npm install -g yarn**
3. **cd optimism-tutorial**
4. **yarn set version berry**
5. **yarn install**
6. **yarn compile**
7. **yarn test**

(I also manually added the safe-buffer dependency to the ganache-core package.json, but it didn't help...and filed a bug on ganache-core here: [https://github.com/trufflesuite/ganache-core/issues/806](https://github.com/trufflesuite/ganache-core/issues/806))

**Comment by platocrat** [comment] 2021-02-27 02:03
hmmm. I see you're using yarn2. I think i might know the fix for this if you're using yarn2. Will check this out to see what's up

**Comment by platocrat** [comment] 2021-02-27 02:04
@mrossesf although, the tests _do_ successfully compile when using `yarn` v1.X or `npm`

**Comment by mrossesf** [comment] 2021-02-27 17:25
@platocrat  Thanks very much for taking a look. Bummer--the `npm test` didn't work for me. Here's the possible reason (unfortunatley, it's long-winded for clarity):

With Yarn 1.22.10 installed globally from my home directory, but then set to 2.4.0 in optimism-tutorial as that's how it's supposed to work per the Yarn 2 installation docs), both verified via `yarn --version`, I originally ran the `yarn install` and `yarn compile` commands successfully. The `yarn compile` command, which per the tutorial "will also make sure Hardhat is installed correctly", finished successfully and asked about providing Hardhat with usage data along the way, so I thought Hardhat was good to go. 

Then I got the `yarn test` error. After getting the `yarn test` error and submitting this bug, I ran `yarn clean` and `yarn compile`, then tried `npm test`. `yarn compile` finished successfully, but without any mention of Hardhat which would seem normal. So, now, you would think Hardhat was correctly installed and `npm test` would work, but instead `npm test` output the following:

```
> yarn clean && hardhat test

sh: hardhat: command not found
npm ERR! Test failed.  See above for more details.
```

Also, I'm wondering if, instead of adding a fix for anyone using Yarn v2 for the tutorial, it might be best to kind of stay with a "Yarn v1.x is recommended" mantra, as by shoe-horning for Yarn v2 users in the tutorial without making all the projects supportive of yarn v2, might that not be setting up people using Yarn v2 just for future errors? So maybe, to handle this Yarn v2 use case for the tutorial right now, the prerequisites section could have the following added after listing Node.js and Git:

"Yarn 1.x (Recommended. If you have Yarn v2 installed, you can alternatively stay on Yarn v2 and try npm as a workaround for any errors.)"

Adding that pre-req would presumably (if my `npm test` issue is due to something else--TBD) solve the issue of Yarn v2 users like me getting `yarn test` errors. I guess though we still have to solve the `npm test` error I got before giving anyone that advice.

**Comment by platocrat** [comment] 2021-02-27 18:40
On a fresh copy of the repo, running `yarn` (after setting the version to yarn2), successfully compiles. 

This means that you can run hardhat by running `yarn hardhat` and all of the other commands like `yarn hardhat compile`, `yarn hardhat clean`, and `yarn hardhat test` -- all of which are have been pre-automated for users within the scripts in the `package.json` so that users only need to run `yarn clean`, `yarn compile`, `yarn test`. 

Nonetheless, you can still use yarn2 to run those scripts. Make sure to keep the `yarn.lock` file when you clone the repo, otherwise, yarn2 will break when you try using it in the repo. 

I actually did run into this issue yesterday evening (I was deleting the lock file), so it's great that you opened up this issue to remind me 😅

**Comment by platocrat** [comment] 2021-02-27 18:46
@mrossesf Let me know if this doesn't solve your issue

**Comment by platocrat** [comment] 2021-02-27 18:48
Whoops, i see the issue is with `yarn test`. Inspecting this now

**Comment by platocrat** [comment] 2021-02-27 19:06
The solution requires adding the dependency shown in the error msg to your `.yarnrc.yml` file, like so:

```
packageExtensions:
  "ganache-core@*":
    dependencies:
      "safe-buffer": "*"
      "randombytes": "*"
      "scryptsy": "*"
      "uuid": "*"


yarnPath: ".yarn/releases/yarn-berry.cjs"
```

Then, you run `yarn` again to update your dependencies. This should let you run the command with the missing dependencies now added. 

However, I'm running into one small issue getting `uuid` to work. So, give me a bit more time to fix this!

**Comment by mrossesf** [comment] 2021-02-27 19:09
Ah, cool...no worries, take your time! I was going to say, I had cloned the tutorial from the main branch recently and hadn't seen any updates to that branch since cloning, and my yarn.lock is intact. FWIW, if I run hardhat --version, I get command not found, but if I run npx hardhat --version, I get 2.0.11.

**Comment by platocrat** [comment] 2021-02-27 19:16
I believe the hardhat CLI requires the `npx` command prefix. It's similar to `npx create-react-app` in that sense

**Comment by mrossesf** [comment] 2021-02-28 15:22
@platocrat  Gonna try to kindly advocate for the doc edit solution one last time, even though it's super cool what you figured out for supporting Yarn 2. The doc edit solution is 2-seconds to implement and would prevent the issue for any user. Think about it from the user's perspective. There are basically two types of users that land on the tutorial and try to follow it:

**Existing Optimism User.** This user is already working on Optimism projects, which means they have Yarn 1. For example, on the optimism-monorepo README.md they learn to install Yarn 1 in [Requirements and Setup](https://github.com/ethereum-optimism/optimism-monorepo#cloning-the-repo).
**New Optimism User.**  This user hasn't worked on Optimism projects at all yet. The first thing they are attempting, like me, is the tutorial, because it's super easy to end up on the tutorial from the [optomism.io](https://optimism.io/).

The only thing the New Optimism User needs in order to avoid the error I encountered is to see a link to the Yarn 1 installation doc in the [Prerequisite Software](http://community.optimism.io/tutorial/#prerequisite-software) section like this:

- Git
- Node.js
- [Yarn 1.x](https://yarnpkg.com/en/docs/install)

As a user myself, I'm already planning to switch to Yarn 1 for the tutorial project, just to keep things simple and only have one source of info to reference for Yarn help, commands, etc.

That said, if you are super close to implementing the Yarn 2 support, and that commit is approved, then it's obviously not a bad thing and you're approach will have validation from others with more clout than me! :-)

**Comment by mrossesf** [comment] 2021-02-28 16:06
Also, if you want to move on to more important tasks, feel free to assign this to me and I'll be happy to make the edit. Thanks

**Comment by platocrat** [comment] 2021-03-02 19:03
Sorry for the late reply! Assigning you right now.

**Comment by mrossesf** [comment] 2021-03-02 19:36
Cool, thanks! I'll get on it as soon as I can.

**Comment by mrossesf** [comment] 2021-03-02 21:16
Switching Yarn from v2 to v1 worked:

![tutorial-yarn-test](https://user-images.githubusercontent.com/13092850/109716268-7e86c780-7b59-11eb-9208-e29e7225b749.png)

**Comment by mrossesf** [comment] 2021-03-02 21:18
@kfichter -- I tried to push my fix to the README.md in the experimental branch, but got permission denied. How should I proceed? Thanks!

**Comment by platocrat** [comment] 2021-03-02 22:00
> @kfichter -- I tried to push my fix to the README.md in the experimental branch, but got permission denied. How should I proceed? Thanks!

You should fork `community-hub`, make your new branch in your forked repo. Then make a PR with that branch. We'll review it and approve it as soon as we complete the review!

**Comment by mrossesf** [comment] 2021-03-03 19:25
Fixed.

**Closed** 2021-03-03 19:25 UTC
Labels: bug
